GET http://localhost:2222/rest

###

GET http://localhost:2222/rest/profile

###

GET http://localhost:2222/rest/spruches

###

POST http://localhost:2222/rest/spruches

{
    "name": "Wolfgang",
    "text": "Wulfgang Spruch",
    "gewicht": 42
}

###

DELETE http://localhost:2222/rest/spruches/1260

###

GET http://localhost:2222/rest/spruches/1

###



# Blatt 7 Aufgabe 4
PUT http://localhost:2222/rest/spruches/1

{
    "name": "Peter",
    "text": "Peter und wulfGANG",
    "gewicht": 17
}

###

POST http://localhost:2222/rest/spruches

{
    "name": "Name1",
    "text": "Spruch1",
    "gewicht": 89
}

###

POST http://localhost:2222/rest/spruches

{
    "name": "Name2",
    "text": "Spruch2",
    "gewicht": 42
}

###

POST http://localhost:2222/rest/spruches

{
    "name": "Name3",
    "text": "Spruch3",
    "gewicht": 17
}

###

POST http://localhost:2222/rest/spruches

{
    "name": "Name4",
    "text": "Spruch4",
    "gewicht": 11
}

###

POST http://localhost:2222/rest/spruches

{
    "name": "Name5",
    "text": "Spruch5",
    "gewicht": 31
}

###



GET http://localhost:2222/rest/spruches?sort=gewicht

###

GET http://localhost:2222/rest/spruches?sort=name,desc

###



GET http://localhost:2222/rest/spruches?size=2&sort=gewicht

###
GET http://localhost:2222/rest/spruches?page=0&size=2&sort=gewicht,asc"
###
GET http://localhost:2222/rest/spruches?page=1&size=2&sort=gewicht,asc"
###
GET http://localhost:2222/rest/spruches?page=2&size=2&sort=gewicht,asc"



# Blatt 7 Aufgabe 5
###
GET http://localhost:2222/rest/spruches/search/findByTextContainingIgnoreCase?suche=wulfgang

###





# Blatt 7 Aufgabe 6
GET http://localhost:2222/rest/tags
###
POST http://localhost:2222/rest/tags

{
    "name": "Hans"
}
###
POST http://localhost:2222/rest/tags

{
    "name": "Peter"
}
###
POST http://localhost:2222/rest/tags

{
    "name": "Adam"
}
###



# Blatt 7 Aufgabe 7

POST http://localhost:2222/rest/spruches

{
    "name": "Name der Beziehung",
    "text": "Text für Beziehung",
    "gewicht": 1515
}
###
GET http://localhost:2222/rest/spruches
###
GET http://localhost:2222/rest/spruches/1409
###
GET http://localhost:2222/rest/tags
###
POST http://localhost:2222/rest/tags

{
    "name": "Ein Tag oder ein Tag?"
}
###
GET http://localhost:2222/rest/tags/1412
###
GET http://localhost:2222/rest/spruches/1409
###
GET http://localhost:2222/rest/spruches/1409/tags
###
POST http://localhost:2222/rest/spruches/1409/tags
Content-Type: text/uri-list

http://localhost:2222/rest/tags/1412
###

DELETE http://localhost:2222/rest/spruches/1409/tags
Content-Type: text/uri-list

http://localhost:2222/rest/tags/1412
###

DELETE http://localhost:2222/rest/tags/1412
###

DELETE http://localhost:2222/rest/spruches/1409/tags/1412
###