GET http://localhost:2222/rest

###

GET http://localhost:2222/rest/profile

###

GET http://localhost:2222/rest/spruches

###

POST http://localhost:2222/rest/spruches

{
    "name": "Wolfgang",
    "text": "Wulfgang Spruch",
    "anspruch": 42
}

###

GET http://localhost:2222/rest/spruches/1

###

PUT http://localhost:2222/rest/spruches/1

{
    "name": "Peter",
    "text": "Peter Spruch",
    "anspruch": 17
}

###
